version: '3.8'

services:

  backend: 
    build: ./services/backend
    ports:
      - 8000:8000 
    environment: 
      - GRAPHHOPPER_API_KEY=38da6050-2777-45ab-ad0c-ac7792c868f0
      - OPENWEATHERMAP_API_KEY=d901498ee217e0dd0697b8b3d83e187a
    command: uvicorn src.app:app --reload --host 0.0.0.0 --port 8000  
      
  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - './app/node_modules'
    ports:
      - 8080:8080
